### ISSUE TITLE
Disable SARIF <> GitHub integration prompt

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/vscode-monokle#16]
When you open a repo a popup appears bottom-right to connect to GitHub. Can we disable this somehow by default? Setting name is `sarif-viewer.connectToGithubCodeScanning`

**Comment by f1ames** [comment]
I think we can disable it (e.g. if it has no value set) on Monokle extension start with [WorkspaceConfiguration API](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration):

```
vscode.workspace.getConfiguration().update(...);
```

**Comment by f1ames** [comment]
Unfortunately, it became more annoying with recent SARIF plugin update which shows another pop-up for GitHub integration:

![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/4de5d392-6f11-4513-99f3-275b208bafcb)

**Comment by f1ames** [comment]
> Unfortunately, it became more annoying with recent SARIF plugin update which shows another pop-up for GitHub integration:
> 
> ![image](https://user-images.githubusercontent.com/1061942/279928997-4de5d392-6f11-4513-99f3-275b208bafcb.png)

Regarding the above, seems like it is connected with notification mentioned in initial description. No matter how I close it, this pop-up always appears (unless you pick `Never`). Seems like a bug to me TBH 🤔 

![monokle 20231102](https://github.com/kubeshop/vscode-monokle/assets/1061942/c7bf51c4-8bef-4c20-88fd-e1417f12b020)

Anyways, disabling initial notification (with e.g. this workaround - https://github.com/kubeshop/vscode-monokle/issues/16#issuecomment-1635575035) should fix this.

**Comment by f1ames** [comment]
Just as quick heads-up - to do it properly we will need to fork Sarif extension. As a workaround, Monokle extension can override Sarif ext setting as mentioned in https://github.com/kubeshop/vscode-monokle/issues/16#issuecomment-1635575035, but this has to caveats:
- It will result in changes in local `.vscode/settings.json` file which might be a bit confusing / not desired by users.
- The `sarif-viewer.connectToGithubCodeScanning` takes effect only after VSC restart, so even when we disable it on the first run it still be visible on this first run (well, still better than for each run).
