### ISSUE TITLE
SARIF viewer is not able to open some resources right after start sometimes

### ISSUE THREAD

**Issue by f1ames** [kubeshop/vscode-monokle#17]
Sometimes when validation is run and you try to go to resource by clicking on errors in SARIF panel, the extension complains that it cannot find related file. However, after going to different resource and getting back it starts to work. Looks like some instability on SARIF ext side.

![monokle 20230717-2](https://github.com/kubeshop/vscode-monokle/assets/1061942/bd25242d-afe1-47c3-b944-80430e7df322)

Maybe related to https://github.com/kubeshop/monokle-core/issues/448 (so #12 indirectly), but I'm not really sure at this stage.

**Comment by olensmar** [comment]
perhaps some async processing that hasn't finished in the background the first time around!?

**Comment by f1ames** [comment]
> perhaps some async processing that hasn't finished in the background the first time around!?

I checked this and waiting (more than 2 minutes) doesn't change anything. It seems that going to resource which can be opened fixes it for broken ones only 🤔  

It also seems it happens only if I have 2 different roots with files with the same name (but still different paths) and it happens only for those files 🤔

**Comment by f1ames** [comment]
Fixed with https://github.com/kubeshop/vscode-monokle/pull/75.

See analysis here of the cause of the issue in https://github.com/kubeshop/vscode-monokle/issues/73.
