### ISSUE TITLE
Usage Telemetry

### ISSUE THREAD

**Issue by olensmar** [kubeshop/vscode-monokle#24]
To understand how we can improve the extension we should collect some basic usage telemetry - as we do for our other projects. This should be enabled by default but have a configuration setting to disable.

Initial events to track:
- install?
- run-command [cmd]
- change-config
- when user selects a problem in the SARIF viewer [problemId]
- when user hovers a problem in the editor
- when user selects [View Problem] in the editor hover [problemId]
- ?

**Comment by f1ames** [comment]
> * install?

Could be first launch or something like this.

> * run-command [cmd]
> * change-config
> * when user hovers a problem in the editor

👍 

> * when user selects a problem in the SARIF viewer [problemId]
> * when user selects [View Problem] in the editor hover [problemId]

Those may require changes in SARIF extension.

**Comment by olensmar** [comment]
that's fine - understand that things happening "inside" SARIF extension components will not be trackable for now..
