### ISSUE TITLE
Hide Monokle when workspace is not Kubernetes related

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/vscode-monokle#41]
Currently, when I open a directory that does not relate to Kubernetes and is not a git repo then I get a subtle error "Monokle: Needs attention" in the status bar at the bottom of VSC. 

In my opinion we should completely hide Monokle when the plugin is irrelevant to the end-user. Great plugins are transparent and you don't notice they are there. The only reason for me to get rid of this indicator is to uninstall the plugin - you don't want to give people those kind of idea!

**Comment by WitoDelnat** [comment]
I've been using the extension for a while and believe we should even go a step further as the red cross with "needs attention" and thinking icon when loading are still to present.

- Icon colors should be the same as the rest of status bas (white by default; might be defined by theme color?)
- Icons on their own are sufficient with good hover text. I would omit text like "needs attention" because text changes cause layout shifts in the status bar which draw unwanted attention. 
- The default logo should maybe be the Monokle logo?
- Thinking icon when loading/working should just be the default logo; it's expected that extensions work in the background and as a user you should not need to be aware of it.

All of this will lead to a much more sober experience which I think will be beneficial. Monokle should be there when you need it and otherwise get out of your way; this is how all good extensions behave.

**Comment by f1ames** [comment]
Looks like custom icons are not supported in status bar (see https://github.com/microsoft/vscode/issues/72244 and https://stackoverflow.com/a/70544972, well, as not part of custom theme).

So either we go with one from [default set](https://code.visualstudio.com/api/references/icons-in-labels) or just a text. Some proposals:

1. Large circle
![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/ecdfb42a-1360-49f0-a07f-5f8e0892c6e6)

2. Small circle
![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/28d347f9-3fc4-4ca1-9c97-4018a06cffb5)

3. `Monokle` text
![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/f0357d0b-d00a-4d21-ab9d-3ca32c9a3840)

4. `M` letter
![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/13f9f013-3a29-443f-a4e0-65780282d633)

Well, apart from dedicated icon, it's just UTF text so we can use any UTF character there (that's how emojis works now), but I haven't found anything suitable TBH. IMHO `Monokle` seems to do the job for me, it's simple, doesn't take too much space and you don't have to wonder where is the icon from.

---

> edit: installing Monokle will also cause both Monokle & Sarif to appear in the bar which both do the same when you click it (i.e. open the validation pane). An alternative is to not show Monokle by default and Monokle only appears when something is off?

On this one, the difference is that both icons when clicked have the same action but Monokle one bring additional information when hovered.

**Comment by f1ames** [comment]
> Currently, when I open a directory that does not relate to Kubernetes and is not a git repo then I get a subtle error "Monokle: Needs attention" in the status bar at the bottom of VSC.
> 
> In my opinion we should completely hide Monokle when the plugin is irrelevant to the end-user. Great plugins are transparent and you don't notice they are there. The only reason for me to get rid of this indicator is to uninstall the plugin - you don't want to give people those kind of idea!

For this I think more static status bar icon does the job, but we also have separate related issue which can improve this further - #38. So even if active folder will not be a git repo it can still be validated with local/default policy.

And going even further, if we want to completely hide Monokle icon, we could detect if project contains any K8s resources. If not just hide all extension related UI. But then it will require a bit smarter approach to restore it when such resources are added. so it's not a quick fix.

**Comment by WitoDelnat** [comment]
We still need an build-in icon for when Monokle needs attention right? What about the following, it's clear this is Monokle and the small-circle is simply there to prevent layout shifts while it has some recognition to our logo. 

```
const icon = needsAttention ? "warning-icon" : "small-circle"
const label = `${icon} Monokle`
```

---

I also had a look at Prettier which might be a decent approach? I like the double checkmark wrt validation

https://github.com/kubeshop/vscode-monokle/assets/7761005/e3a2185a-aea6-41f6-8106-d0df9a14d192

---

Wrt hiding, if its not a quick-fix then let's split that for a separate task and tackle it later. This more sober experience will make that less urgent.

**Comment by f1ames** [comment]
Ok, yes, let's have the icon so we can show invalid status. I went with first proposal = circle + warning icons.

As for hiding, I extracted it to separate issue as it is more broader than just hiding an icon, see #44.
