### ISSUE TITLE
Validate on edit vs save

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/vscode-monokle#49]
Currently Monokle Validation runs on saving files as compared to saving. This takes away a small part of the real-time validation. Is there a possibility to do this on a debounced editing to give feedback earlier?

**Comment by f1ames** [comment]
Should be doable with `onDidChangeTextDocument` (or something similar) from [workspace](https://code.visualstudio.com/api/references/vscode-api#workspace) namespace.

**Comment by f1ames** [comment]
It should be configurable to validate `onType` or `onSave` as e.g. ESLint ext does:

![image](https://github.com/kubeshop/vscode-monokle/assets/1061942/dc7ac00b-4efa-4ad2-b17c-f66999c91900)
