### ISSUE TITLE
Add config option when to show validation panel

### ISSUE THREAD

**Issue by f1ames** [kubeshop/vscode-monokle#6]
The validation panel (SARIF panel) is always shown on startup when there are any resources with validation warning/errors. It might be a bit annoying in a long run.

This behavior should become a configuration option.

**IMPORTANT**: This is how [SARIF `openLogs()` behaves](https://github.com/microsoft/sarif-vscode-extension/blob/b086b9a415975c37bfafc7444e1aba4f289cfc76/src/extension/index.ts#L92-L96), so either it will require changes in SARIF extension or a workaround (passing file with no errors to `openLogs()` API and then populating with validation results). I think contributing would be a viable option here definately.

**Comment by f1ames** [comment]
The simplest solution would be adding config option for users to decide when Violations panel should be shown automatically:
- never
- on project open (this is how it behaves now)
- on new violations (so every time list of violations changes - well, to be precise it should be when there are different violations than in a previous run, so e.g. suppressing should open it IMHO, but changing policy would likely trigger that) (maybe?)

**Comment by WitoDelnat** [comment]
As another option, I wonder if from the highlight or an action we could maybe have a link that "Show details" or something like that. Actually similarly to ESLint now that I think about it (see screenshot below). This is less in your face, but there if you'd like it and more easily discoverable.

![Screenshot 2024-01-26 at 14 42 25](https://github.com/kubeshop/vscode-monokle/assets/7761005/122ac590-cc45-4dce-9ff8-218a607b401c)

**Comment by f1ames** [comment]
> As another option, I wonder if from the highlight or an action we could maybe have a link that "Show details" or something like that. Actually similarly to ESLint now that I think about it (see screenshot below). This is less in your face, but there if you'd like it and more easily discoverable.
> 
> ...
> 
> ![Screenshot 2024-01-26 at 14 42 25](https://private-user-images.githubusercontent.com/7761005/300001069-122ac590-cc45-4dce-9ff8-218a607b401c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzcwMjIsIm5iZiI6MTcwNjI3NjcyMiwicGF0aCI6Ii83NzYxMDA1LzMwMDAwMTA2OS0xMjJhYzU5MC1jYzQ1LTRkY2UtOWZmOC0yMThhNjA3YjQwMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTM0NTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVkZWZiMWIyOTVlYTY2MWRmNjQ1Zjk4M2EyMTM2YjIxNWJhMzhmMTIwNmZiNWZjZjg5ZjljNTJkYTg5YTFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bwDfKBNfFvhBK7Qsrz434IUpAwFcOHHgityKkWdfWBI)

For a moment I was thinking about this too, this could be useful 🤔

> One downside I can think of is that often problems overlap in Kubernetes which would lead to too many available actions. To illustrate, it's 3 per problem and you can have like 5 together easily so 15 actions which is way to many 🤔

Regarding the above, this could be an issue indeed. Should we have a generic quick fix action like "Show documentation/details for violated rules" which will just open the panel then?

> Maybe at that point we should encourage opening the SARIF viewer and action from there?

What do you mean exactly, just to leave it as is? I mean go with initial proposal for introducing config or something different?

**Comment by WitoDelnat** [comment]
> Regarding the above, this could be an issue indeed. Should we have a generic quick fix action like "Show documentation/details for violated rules" which will just open the panel then?

+1 for making it one single action for "Show more details for these rules".

> What do you mean exactly, just to leave it as is? I mean go with initial proposal for introducing config or something different?

I don't remember if its currently possible to fix or suppress from the SARIF Details pane. What I mean is that if we have like 15+ fix/suppress actions it becomes too much and as an alternative the action could then be merged as "Fix these problems in SARIF viewer" which opens the pane and you can manage it there. I doubt a bit if this idea feels as a good UX though.
